[tool.poetry]
name = "magicsquare"
version = "1.0.0"
description = ""
authors = ["João Santos <joaopns05@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
ortools = "^8.2.8710"

[tool.poetry.dev-dependencies]
yapf = "^0.31.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
